'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(";")>  _
        Public Property Delimitador() As String
            Get
                Return CType(Me("Delimitador"),String)
            End Get
            Set
                Me("Delimitador") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(",")>  _
        Public Property SepDecimal() As Char
            Get
                Return CType(Me("SepDecimal"),Char)
            End Get
            Set
                Me("SepDecimal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("com azimute")>  _
        Public Property Mazimute() As String
            Get
                Return CType(Me("Mazimute"),String)
            End Get
            Set
                Me("Mazimute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("confrontando com terras de")>  _
        Public Property Mconfronto() As String
            Get
                Return CType(Me("Mconfronto"),String)
            End Get
            Set
                Me("Mconfronto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("definido pelas coordenadas")>  _
        Public Property MCoord() As String
            Get
                Return CType(Me("MCoord"),String)
            End Get
            Set
                Me("MCoord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("e distância de")>  _
        Public Property Mdist() As String
            Get
                Return CType(Me("Mdist"),String)
            End Get
            Set
                Me("Mdist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("segue por")>  _
        Public Property Mdivisa() As String
            Get
                Return CType(Me("Mdivisa"),String)
            End Get
            Set
                Me("Mdivisa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:")>  _
        Public Property Meste() As String
            Get
                Return CType(Me("Meste"),String)
            End Get
            Set
                Me("Meste") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("encerrando este perímetro.")>  _
        Public Property Mfim() As String
            Get
                Return CType(Me("Mfim"),String)
            End Get
            Set
                Me("Mfim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inicia-se a descrição deste perímetro no vértice")>  _
        Public Property Minicio() As String
            Get
                Return CType(Me("Minicio"),String)
            End Get
            Set
                Me("Minicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("até o vértice")>  _
        Public Property Mligacao() As String
            Get
                Return CType(Me("Mligacao"),String)
            End Get
            Set
                Me("Mligacao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N:")>  _
        Public Property Mnorte() As String
            Get
                Return CType(Me("Mnorte"),String)
            End Get
            Set
                Me("Mnorte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Mrepeticao() As Boolean
            Get
                Return CType(Me("Mrepeticao"),Boolean)
            End Get
            Set
                Me("Mrepeticao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Memorial descritivo")>  _
        Public Property Mtitulo() As String
            Get
                Return CType(Me("Mtitulo"),String)
            End Get
            Set
                Me("Mtitulo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("m")>  _
        Public Property Munidade() As String
            Get
                Return CType(Me("Munidade"),String)
            End Get
            Set
                Me("Munidade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Pcidade() As String
            Get
                Return CType(Me("Pcidade"),String)
            End Get
            Set
                Me("Pcidade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Pprofissional() As String
            Get
                Return CType(Me("Pprofissional"),String)
            End Get
            Set
                Me("Pprofissional") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Pregistro() As String
            Get
                Return CType(Me("Pregistro"),String)
            End Get
            Set
                Me("Pregistro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Pdata() As String
            Get
                Return CType(Me("Pdata"),String)
            End Get
            Set
                Me("Pdata") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNTit() As Boolean
            Get
                Return CType(Me("NchkNTit"),Boolean)
            End Get
            Set
                Me("NchkNTit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNImo() As Boolean
            Get
                Return CType(Me("NchkNImo"),Boolean)
            End Get
            Set
                Me("NchkNImo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNImoV() As Boolean
            Get
                Return CType(Me("NchkNImoV"),Boolean)
            End Get
            Set
                Me("NchkNImoV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNMun() As Boolean
            Get
                Return CType(Me("NchkNMun"),Boolean)
            End Get
            Set
                Me("NchkNMun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNMunV() As Boolean
            Get
                Return CType(Me("NchkNMunV"),Boolean)
            End Get
            Set
                Me("NchkNMunV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNMat() As Boolean
            Get
                Return CType(Me("NchkNMat"),Boolean)
            End Get
            Set
                Me("NchkNMat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNMatV() As Boolean
            Get
                Return CType(Me("NchkNMatV"),Boolean)
            End Get
            Set
                Me("NchkNMatV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNCom() As Boolean
            Get
                Return CType(Me("NchkNCom"),Boolean)
            End Get
            Set
                Me("NchkNCom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNComV() As Boolean
            Get
                Return CType(Me("NchkNComV"),Boolean)
            End Get
            Set
                Me("NchkNComV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNCar() As Boolean
            Get
                Return CType(Me("NchkNCar"),Boolean)
            End Get
            Set
                Me("NchkNCar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNCarV() As Boolean
            Get
                Return CType(Me("NchkNCarV"),Boolean)
            End Get
            Set
                Me("NchkNCarV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNInc() As Boolean
            Get
                Return CType(Me("NchkNInc"),Boolean)
            End Get
            Set
                Me("NchkNInc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNIncV() As Boolean
            Get
                Return CType(Me("NchkNIncV"),Boolean)
            End Get
            Set
                Me("NchkNIncV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNAre() As Boolean
            Get
                Return CType(Me("NchkNAre"),Boolean)
            End Get
            Set
                Me("NchkNAre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNAreV() As Boolean
            Get
                Return CType(Me("NchkNAreV"),Boolean)
            End Get
            Set
                Me("NchkNAreV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNPer() As Boolean
            Get
                Return CType(Me("NchkNPer"),Boolean)
            End Get
            Set
                Me("NchkNPer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNPerV() As Boolean
            Get
                Return CType(Me("NchkNPerV"),Boolean)
            End Get
            Set
                Me("NchkNPerV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNPro() As Boolean
            Get
                Return CType(Me("NchkNPro"),Boolean)
            End Get
            Set
                Me("NchkNPro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNProV() As Boolean
            Get
                Return CType(Me("NchkNProV"),Boolean)
            End Get
            Set
                Me("NchkNProV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNPto() As Boolean
            Get
                Return CType(Me("NchkNPto"),Boolean)
            End Get
            Set
                Me("NchkNPto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNCoo() As Boolean
            Get
                Return CType(Me("NchkNCoo"),Boolean)
            End Get
            Set
                Me("NchkNCoo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNDis() As Boolean
            Get
                Return CType(Me("NchkNDis"),Boolean)
            End Get
            Set
                Me("NchkNDis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNAzi() As Boolean
            Get
                Return CType(Me("NchkNAzi"),Boolean)
            End Get
            Set
                Me("NchkNAzi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNCon() As Boolean
            Get
                Return CType(Me("NchkNCon"),Boolean)
            End Get
            Set
                Me("NchkNCon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNDiv() As Boolean
            Get
                Return CType(Me("NchkNDiv"),Boolean)
            End Get
            Set
                Me("NchkNDiv") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNCid() As Boolean
            Get
                Return CType(Me("NchkNCid"),Boolean)
            End Get
            Set
                Me("NchkNCid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NchkNDat() As Boolean
            Get
                Return CType(Me("NchkNDat"),Boolean)
            End Get
            Set
                Me("NchkNDat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNNom() As Boolean
            Get
                Return CType(Me("NchkNNom"),Boolean)
            End Get
            Set
                Me("NchkNNom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NchkNReg() As Boolean
            Get
                Return CType(Me("NchkNReg"),Boolean)
            End Get
            Set
                Me("NchkNReg") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.gera_memorial.My.MySettings
            Get
                Return Global.gera_memorial.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
